version: "3.4"
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
      target: master
    ports:
      - "8080:8080"
    volumes:
      - ./data:/usr/src/hiro/data
    environment:
      - PORT=8080
        # - DATA_OUT_DIR=/usr/src/hiro/data
  worker_1:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    ports:
      - "5002:5002"
    volumes:
      - ./data:/usr/src/hiro/data
    environment:
      - PORT=5002
        # - DATA_OUT_DIR=/usr/src/hiro/data
  worker_2:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    ports:
      - "5003:5003"
    volumes:
      - ./data:/usr/src/hiro/data
        # - DATA_OUT_DIR=/usr/src/hiro/data
    environment:
      - PORT=5003
